# Generated by Django 4.1.6 on 2023-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_course_id_alter_courseallocation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("First", "First"),
                    ("Second", "Second"),
                    ("Third", "Third"),
                    ("Fourth", "Fourth"),
                    ("Fifth", "Fifth"),
                    ("Sixth", "Sixth"),
                    ("Seventh", "Seventh"),
                    ("Eighth", "Eighth"),
                ],
                max_length=200,
            ),
        ),
    ]
