# Generated by Django 4.1.6 on 2023-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_newsandevents_id_alter_semester_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="is_current_semester",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First", "First"),
                    ("Second", "Second"),
                    ("Third", "Third"),
                    ("Fourth", "Fourth"),
                ],
                max_length=10,
            ),
        ),
    ]
