# Generated by Django 4.1.6 on 2023-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_semester_is_current_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First", "First"),
                    ("Second", "Second"),
                    ("Third", "Third"),
                    ("Fourth", "Fourth"),
                    ("Fifth", "Fifth"),
                    ("Sixth", "Sixth"),
                    ("Seventh", "Seventh"),
                    ("Eighth", "Eighth"),
                ],
                max_length=10,
            ),
        ),
    ]
